name: 'Baidu Tieba Auto Sign'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '5 18,22 * * ?'

jobs:
  tieba_sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set Python to specific versions'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.16'
      - name: 'Try next Python version if the previous one fails'
        if: failure() 
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.11'
      - name: 'Try next Python version if the previous one fails'
        if: failure() 
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.9'
      - name: 'Try next Python version if the previous one fails'
        if: failure() 
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'
      - name: 'Try next Python version if the previous one fails'
        if: failure() 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.21'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        run: python main.py

